# -*- coding: utf-8 -*-
"""
/***************************************************************************
 InformatykaPlugin
                                 A QGIS plugin
 Wtyczka licząca przewyższenia pomiędzy punktami na warstwie oraz pole powierzchni metodą Gaussa
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-06-10
        copyright            : (C) 2024 by Piotr Wieczorek
        email                : Piotr9110@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load InformatykaPlugin class from file InformatykaPlugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .informatyka_plugin import InformatykaPlugin
    return InformatykaPlugin(iface)
