# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'informatyka_plugin_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InformatykaPluginDialogBase(object):
    def setupUi(self, InformatykaPluginDialogBase):
        InformatykaPluginDialogBase.setObjectName("InformatykaPluginDialogBase")
        InformatykaPluginDialogBase.resize(400, 300)
        self.pushButtonElevation = QtWidgets.QPushButton(InformatykaPluginDialogBase)
        self.pushButtonElevation.setGeometry(QtCore.QRect(200, 100, 93, 28))
        self.pushButtonElevation.setObjectName("pushButtonElevation")
        self.labelArea = QtWidgets.QLabel(InformatykaPluginDialogBase)
        self.labelArea.setGeometry(QtCore.QRect(20, 140, 171, 20))
        self.labelArea.setObjectName("labelArea")
        self.labelAreaResult = QtWidgets.QLabel(InformatykaPluginDialogBase)
        self.labelAreaResult.setGeometry(QtCore.QRect(300, 150, 81, 20))
        self.labelAreaResult.setText("")
        self.labelAreaResult.setObjectName("labelAreaResult")
        self.pushButtonArea = QtWidgets.QPushButton(InformatykaPluginDialogBase)
        self.pushButtonArea.setGeometry(QtCore.QRect(200, 140, 93, 28))
        self.pushButtonArea.setObjectName("pushButtonArea")
        self.labelElevationResult = QtWidgets.QLabel(InformatykaPluginDialogBase)
        self.labelElevationResult.setGeometry(QtCore.QRect(300, 110, 81, 20))
        self.labelElevationResult.setText("")
        self.labelElevationResult.setObjectName("labelElevationResult")
        self.button_box = QtWidgets.QDialogButtonBox(InformatykaPluginDialogBase)
        self.button_box.setGeometry(QtCore.QRect(110, 240, 181, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.mLayerChoose = QgsMapLayerComboBox(InformatykaPluginDialogBase)
        self.mLayerChoose.setGeometry(QtCore.QRect(100, 40, 160, 27))
        self.mLayerChoose.setObjectName("mLayerChoose")
        self.labelChooseLayer = QtWidgets.QLabel(InformatykaPluginDialogBase)
        self.labelChooseLayer.setGeometry(QtCore.QRect(130, 10, 171, 16))
        self.labelChooseLayer.setObjectName("labelChooseLayer")
        self.labelElevation = QtWidgets.QLabel(InformatykaPluginDialogBase)
        self.labelElevation.setGeometry(QtCore.QRect(40, 100, 151, 16))
        self.labelElevation.setObjectName("labelElevation")

        self.retranslateUi(InformatykaPluginDialogBase)
        QtCore.QMetaObject.connectSlotsByName(InformatykaPluginDialogBase)

    def retranslateUi(self, InformatykaPluginDialogBase):
        _translate = QtCore.QCoreApplication.translate
        InformatykaPluginDialogBase.setWindowTitle(_translate("InformatykaPluginDialogBase", "Informatyka_Plugin"))
        self.pushButtonElevation.setText(_translate("InformatykaPluginDialogBase", "Oblicz "))
        self.labelArea.setText(_translate("InformatykaPluginDialogBase", "Obliczenie pola powierzchni"))
        self.pushButtonArea.setText(_translate("InformatykaPluginDialogBase", "Oblicz"))
        self.labelChooseLayer.setText(_translate("InformatykaPluginDialogBase", "Wybierz warstwę"))
        self.labelElevation.setText(_translate("InformatykaPluginDialogBase", "Obliczenie przewyższenia"))
from qgsmaplayercombobox import QgsMapLayerComboBox
